# -*- coding: utf-8 -*-
"""ShAI_BootCamp_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SaiGEe-4cVL0hlBRUox8RktQQDo9LaU8

#About Dataset
salaries dataset generally provides information about the employees of an organization in relation to their compensation. It typically includes details such as how much each employee is paid (their salary), their job titles, the departments they work in, and possibly additional information like their level of experience, education, and employment history within the organization.

# Features
- 'Id'
- 'EmployeeName'
- 'JobTitle'
- 'BasePay'
- 'OvertimePay'
- 'OtherPay'
- 'Benefits'
- 'TotalPay' -> salary
- 'TotalPayBenefits'
- 'Year'
- 'Notes'
- 'Agency'
- 'Status'

# Tasks

1. **Basic Data Exploration**: Identify the number of rows and columns in the dataset, determine the data types of each column, and check for missing values in each column.

2. **Descriptive Statistics**: Calculate basic statistics mean, median, mode, minimum, and maximum salary, determine the range of salaries, and find the standard deviation.

3. **Data Cleaning**: Handle missing data by suitable method with explain why you use it.

4. **Basic Data Visualization**: Create histograms or bar charts to visualize the distribution of salaries, and use pie charts to represent the proportion of employees in different departments.

5. **Grouped Analysis**: Group the data by one or more columns and calculate summary statistics for each group, and compare the average salaries across different groups.

6. **Simple Correlation Analysis**: Identify any correlation between salary and another numerical column, and plot a scatter plot to visualize the relationship.

8. **Summary of Insights**: Write a brief report summarizing the findings and insights from the analyses.

# Very Important Note
There is no fixed or singular solution for this assignment, so if anything is not clear, please do what you understand and provide an explanation.
"""

import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('/content/Salaries.csv')
df.head()

df.columns

"""# **1. Basic Data Exploration**"""

# (Number of rows, Number of columns)
num_rows, num_columns = df.shape
print("Number of rows = ", num_rows, "\nnumber of columns = ", num_columns)

# Determine data types for each column
df.dtypes

#Check for missing values in each column
df.isnull().sum()

"""# **2. Descriptive Statistics**"""

#Calculate the mean of the salaries "which is the column named [TotalPay]"
df['TotalPay'].mean()

#Calculate the median of the salaries "which is the column named [TotalPay]"
df['TotalPay'].median()

#Calculate the mode of the salaries "which is the column named [TotalPay]"
df['TotalPay'].mode()[0]

#Calculate the minimum salary
mini_salary = df['TotalPay'].min()
mini_salary

#Calculate the maximum salary
max_salary = df['TotalPay'].max()
max_salary

#Calculate the range of salaries
range = max_salary - mini_salary
range

#Calculate the standard deviation of the salaries
df['TotalPay'].std()

# Or we can recap all that by calling the describe function, which will get all the descriptive statistics for all the columns
df.describe()

"""# **3. Data Cleaning**"""

# let's drop rows with missing values (simplest method)
df.dropna().isnull().sum()

#Another method is to fill the missing cells with the mean value of the same column
#This method is more efficient in critical data
mean_total_pay = df['TotalPay'].mean()
df['TotalPay'].fillna(mean_total_pay, inplace=True)  #inplace makes sure that the changes are made and are permanent
df['TotalPay'].isnull().sum()

#Drop some unnecessary columns
col_drop = ['Notes', 'Status']
df.drop(columns = col_drop , inplace = True)
df

"""# **4. Basic Data Visualization**"""

import matplotlib.pyplot as plt

#Histogram to describe the distribution of salaries
#The term "frequency" refers to the number of times a particular value or range of values occurs in a dataset
plt.figure(figsize=(9, 3))
plt.hist(df['TotalPay'], bins=30, color='skyblue', edgecolor='black')
plt.title('Salary Distribution')
plt.xlabel('Salary')
plt.ylabel('Frequency')
plt.show()

# Pie chart for department proportions
department_proportions = df['JobTitle'].value_counts()
plt.figure(figsize=(20, 20))
plt.pie(department_proportions, labels=department_proportions.index, autopct='%1.1f%%', startangle=90, pctdistance=0.85, colors=plt.cm.Paired.colors)
plt.title('Job Title Distribution')
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""# **5. Grouped Analysis**"""

#Grouping the Department by the salary columns and calculating all the statisctics
grouped_by_department = df.groupby('JobTitle')['TotalPay'].describe()
grouped_by_department

#Grouping the year by the salary columns and calculating all the statisctics
grouped_by_year = df.groupby('Year')['TotalPay'].describe()
grouped_by_year

"""# **6. Simple Correlation Analysis**"""

#Calculating the correlation between BasePay and salary
correlation = df['TotalPay'].corr(df['BasePay'])
correlation

#Visualizing the relationship between Basepay and TotalPay
import seaborn as sns
plt.figure(figsize=(10, 6))
sns.scatterplot(x = df['BasePay'], y = df['TotalPay'])
plt.title(f'Scatter Plot: TotalPay vs BasePay')
plt.xlabel('BasePay')
plt.ylabel('TotalPay')
plt.show()

"""# **7. Summary Of Insights**

Upon analyzing the dataset, several key insights emerged:
The dataset, encompassing employee details such as job titles, salaries, and related information, revealed a diverse workforce.

Through descriptive statistics, I discerned interesting patterns in the distribution of salaries, providing a comprehensive view of the compensation landscape.

Addressing missing values became crucial for maintaining data integrity, and I opted for two methods (dropping missing values, replacing missing values in salaries with the normalized value), i also dropped some unnecessary columns like "Notes and Sattus", they were Null columns.

 Visualizations, including histograms and pie charts, brought clarity to the distribution of salaries and the proportion of employees across different job titles.

 Grouped analyses, particularly by 'JobTitle' and 'Year', uncovered variations in average salaries, offering a nuanced understanding of trends within the organization.

 Correlation analyses between total salary and base salary shed light on potential relationships, and scatter plots visually represented these associations.

 Overall, the analyses provided a holistic view of the workforce, offering valuable insights into salary structures, distribution, and potential trends over different years and job titles. These findings pave the way for informed decision-making and potential areas of focus for further exploration or action.

# Good Luck!
"""